#!/usr/bin/env bash
# scripts/doctor.sh — Check all prerequisites and configuration health.
# Run via: make doctor  (or: make doctor-offline)
# Exit codes: 0 = all OK or warnings only, 1 = one or more FAIL checks.
#
# Flags:
#   --offline   Skip network-dependent checks (registry reachability)

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

OFFLINE=0
for arg in "$@"; do
  case "$arg" in
    --offline) OFFLINE=1 ;;
  esac
done

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

PASS=0
WARN=0
FAIL=0

_ok()   { printf "  ${GREEN}✅  %-35s${NC}  %s\n" "$1" "${2:-}"; PASS=$((PASS+1)); }
_warn() { printf "  ${YELLOW}⚠️   %-35s${NC}  %s\n" "$1" "${2:-}"; WARN=$((WARN+1)); }
_fail() { printf "  ${RED}❌  %-35s${NC}  %s\n" "$1" "${2:-}"; FAIL=$((FAIL+1)); }

echo ""
echo -e "${BOLD}┌─── MOPS Portal — Doctor ─────────────────────────────────────────┐${NC}"
echo ""

# ── 1. Required tools ──────────────────────────────────────────────────────────
echo -e "  ${CYAN}§ Tools${NC}"

_check_version() {
  local cmd="$1" label="$2" min_major="$3" version_flag="${4:---version}"
  if ! command -v "$cmd" &>/dev/null; then
    _fail "$label" "not installed — see https://nodejs.org"
    return
  fi
  local ver major
  ver=$("$cmd" $version_flag 2>/dev/null | head -1 | grep -oE '[0-9]+\.[0-9]+' | head -1)
  major=$(echo "$ver" | cut -d. -f1)
  if [[ -z "$major" || ! "$major" =~ ^[0-9]+$ ]]; then
    _warn "$label" "installed but version unreadable"
    return
  fi
  if (( major < min_major )); then
    _fail "$label" "v${ver} — need ≥${min_major}.x"
  else
    _ok  "$label" "v${ver}"
  fi
}

_check_version node "Node.js ≥ 18" 18 "--version"
_check_version npm  "npm ≥ 8"       8  "--version"

if ! command -v docker &>/dev/null; then
  _fail "Docker" "not installed — https://docs.docker.com/get-docker/"
else
  _docker_ver=$(docker version --format '{{.Server.Version}}' 2>/dev/null || echo "")
  if [[ -z "$_docker_ver" ]]; then
    _fail "Docker daemon" "not running — run: sudo systemctl start docker"
  else
    _ok "Docker" "v${_docker_ver} (daemon OK)"
  fi
fi

if docker compose version &>/dev/null 2>&1; then
  _dc_ver=$(docker compose version --short 2>/dev/null || echo "")
  _ok "Docker Compose v2" "v${_dc_ver}"
elif command -v docker-compose &>/dev/null; then
  _warn "Docker Compose" "using legacy v1 (docker-compose) — upgrade to v2 recommended"
else
  _fail "Docker Compose" "not found — https://docs.docker.com/compose/install/"
fi

command -v git     &>/dev/null && _ok  "git"     "$(git --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')" \
                                || _fail "git"     "not installed"
command -v curl    &>/dev/null && _ok  "curl"    "$(curl --version | head -1 | awk '{print $2}')" \
                                || _warn "curl"    "not installed (needed for health checks)"
command -v openssl &>/dev/null && _ok  "openssl" "$(openssl version | awk '{print $2}')" \
                                || _warn "openssl" "not installed (fallback /dev/urandom will be used for secret generation)"

echo ""

# ── 2. .env health ──────────────────────────────────────────────────────────────
echo -e "  ${CYAN}§ Configuration${NC}"

if [[ ! -f .env ]]; then
  _fail ".env" "missing — run ./setup.sh first"
else
  _ok ".env" "present"

  # Check for keys in .env.example but missing from .env
  if [[ -f .env.example ]]; then
    MISSING=()
    while IFS= read -r line; do
      [[ "$line" =~ ^[[:space:]]*# ]] && continue
      [[ -z "${line// }" ]] && continue
      key="${line%%=*}"
      [[ -z "$key" ]] && continue
      grep -q "^${key}=" .env 2>/dev/null || MISSING+=("$key")
    done < .env.example
    if [[ ${#MISSING[@]} -gt 0 ]]; then
      _warn ".env completeness" "${#MISSING[@]} keys missing from .env.example — run: make sync-env"
    else
      _ok ".env completeness" "all .env.example keys present"
    fi
  fi

  # Secret strength (inline — don't call validate_env to avoid dependency)
  set -a; source .env 2>/dev/null || true; set +a
  _jwt="${LOCAL_JWT_SECRET:-}"
  if [[ -z "$_jwt" || "$_jwt" == "change-me-in-production" || "$_jwt" == "<auto-generated-by-setup.sh>" ]]; then
    _fail "LOCAL_JWT_SECRET" "missing or placeholder — run ./setup.sh"
  elif [[ ${#_jwt} -lt 32 ]]; then
    _fail "LOCAL_JWT_SECRET" "too short (${#_jwt} chars, need ≥32)"
  else
    _ok "LOCAL_JWT_SECRET" "${#_jwt} chars"
  fi

  _pgpass="${POSTGRES_PASSWORD:-}"
  if [[ -z "$_pgpass" || "$_pgpass" == "portal_secret" || "$_pgpass" == "<auto-generated-by-setup.sh>" ]]; then
    _fail "POSTGRES_PASSWORD" "missing or insecure default — run ./setup.sh"
  else
    _ok "POSTGRES_PASSWORD" "set"
  fi

  _admin="${VITE_ADMIN_USERS:-}"
  [[ -n "$_admin" ]] && _ok "VITE_ADMIN_USERS" "$_admin" \
                      || _fail "VITE_ADMIN_USERS" "not set"

  # Check deploy/env.example contains all keys needed for the pipeline
  if [[ -f deploy/env.example ]]; then
    DEPLOY_MISSING=()
    for key in POSTGRES_PASSWORD LOCAL_JWT_SECRET NPM_USER NPM_PASSWORD VITE_ADMIN_USERS VITE_OIDC_CLIENT_ID CORS_ORIGIN CONFLUENCE_USERNAME CONFLUENCE_PASSWORD; do
      grep -q "^${key}=" deploy/env.example 2>/dev/null || \
        grep -q "^# ${key}=" deploy/env.example 2>/dev/null || \
        DEPLOY_MISSING+=("$key")
    done
    if [[ ${#DEPLOY_MISSING[@]} -gt 0 ]]; then
      _warn "deploy/env.example" "${#DEPLOY_MISSING[@]} pipeline keys missing: ${DEPLOY_MISSING[*]}"
    else
      _ok "deploy/env.example" "all pipeline keys documented"
    fi
  fi
fi

echo ""

# ── 3. Port availability ────────────────────────────────────────────────────────
echo -e "  ${CYAN}§ Ports${NC}"

_check_port() {
  local port="$1" label="$2"
  if command -v ss &>/dev/null; then
    ss -tlnp 2>/dev/null | grep -q ":${port} " && { _warn "Port $port ($label)" "already in use"; return; }
  elif command -v lsof &>/dev/null; then
    lsof -i :"$port" -sTCP:LISTEN &>/dev/null 2>&1 && { _warn "Port $port ($label)" "already in use"; return; }
  fi
  _ok "Port $port ($label)" "available"
}

_check_port 80   "nginx/prod"
_check_port 3001 "backend"
_check_port 5173 "Vite dev"
_check_port 8080 "mock OIDC"

echo ""

# ── 4. Network / registry ──────────────────────────────────────────────────────
echo -e "  ${CYAN}§ Network${NC}"

if [[ "$OFFLINE" -eq 1 ]]; then
  _ok "Offline mode" "network checks skipped (--offline)"
else
  # Use curl for registry reachability checks — it honours shell proxy env vars
  # (HTTP_PROXY / HTTPS_PROXY) and does not require a specific image to exist.
  # Any HTTP response (including 401 auth-required) means the registry is up.
  if ! command -v curl &>/dev/null; then
    _warn "Network checks" "curl not installed — skipping registry reachability"
  else
    # Build curl TLS options: trust the corporate CA cert when NODE_EXTRA_CA_CERTS is set.
    _curl_tls_opts=()
    if [[ -n "${NODE_EXTRA_CA_CERTS:-}" && -f "$NODE_EXTRA_CA_CERTS" ]]; then
      _curl_tls_opts=(--cacert "$NODE_EXTRA_CA_CERTS")
    fi

    _registry="${DOCKER_REGISTRY:-}"
    if [[ -n "$_registry" ]]; then
      # Strip any repository-path suffix; preserve host:port when present.
      # e.g. "myregistry.example.com/dockerhub-proxy"  → "myregistry.example.com"
      #      "myregistry.example.com:5000/proxy"        → "myregistry.example.com:5000"
      _registry_host="${_registry%%/*}"
      _registry_url="https://${_registry_host}/v2/"
    else
      _registry_url="https://registry-1.docker.io/v2/"
    fi
    _http_code=$(curl -o /dev/null -sw "%{http_code}" --max-time 10 "${_curl_tls_opts[@]}" "$_registry_url" 2>/dev/null || echo "000")
    if [[ "$_http_code" =~ ^[2-4][0-9][0-9]$ ]]; then
      _ok "Docker registry" "${_registry:-Docker Hub} — reachable (HTTP ${_http_code})"
    else
      _warn "Docker registry" "${_registry:-Docker Hub} — unreachable (HTTP ${_http_code}; set DOCKER_REGISTRY in .env if behind a proxy)"
    fi

    # Check npm registry reachability with curl rather than npm ping.
    # npm ping requires a registry-specific endpoint not all mirrors expose.
    _npm_registry=$(npm config get registry 2>/dev/null || echo "https://registry.npmjs.org/")
    _npm_code=$(curl -o /dev/null -sw "%{http_code}" --max-time 10 "${_curl_tls_opts[@]}" "$_npm_registry" 2>/dev/null || echo "000")
    if [[ "$_npm_code" =~ ^[2-4][0-9][0-9]$ ]]; then
      _ok "npm registry" "${_npm_registry} — reachable (HTTP ${_npm_code})"
    else
      _warn "npm registry" "${_npm_registry} — unreachable (HTTP ${_npm_code}; set NPM_REGISTRY in registry.env)"
    fi
  fi
fi

echo ""

# ── Summary ─────────────────────────────────────────────────────────────────────
echo -e "${BOLD}└──────────────────────────────────────────────────────────────────┘${NC}"
echo ""
printf "  %b%d passed%b  |  %b%d warnings%b  |  %b%d failed%b\n" \
  "$GREEN" "$PASS" "$NC"  "$YELLOW" "$WARN" "$NC"  "$RED" "$FAIL" "$NC"
echo ""

if [[ "$FAIL" -gt 0 ]]; then
  echo -e "  ${RED}Doctor found ${FAIL} critical issue(s). Fix them before running ./setup.sh.${NC}"
  echo ""
  exit 1
elif [[ "$WARN" -gt 0 ]]; then
  echo -e "  ${YELLOW}Doctor found ${WARN} warning(s). Setup will likely work but review above.${NC}"
  echo ""
  exit 0
else
  echo -e "  ${GREEN}All checks passed! Ready to run ./setup.sh${NC}"
  echo ""
  exit 0
fi
